<?php

$string = "Use the switch context button in the upper left corner of this page to switch between your personal context (arewolf) and organizations you are a member of.";
$stringHtml = "<b>Use the switch context button in the upper left corner of this page to switch between your personal context (arewolf) and organizations you are a member of.</b>";
echo strlen($string);
echo "<br>";
echo strpos($string, 'the'); 
echo "<br>";
echo "<br>";
echo substr($string, 4, 3);
echo "<br>";
echo "<br>";
echo $string;
echo "<br>";
echo "<br>";
echo "<br>";
$stringArray = explode(" ", $string); //explode(delimiter, $string[, int $limit]) 
print_r($stringArray);
echo "<br>";
echo "<br>";
echo "<br>";
$b2string = implode(" ", $stringArray);
echo $b2string;
echo "<br>";
echo "<br>";
echo "<br>";
echo ucwords($string);
echo "<br>";
echo "<br>";
echo "<br>";
echo substr($string, (strpos($string, 'Use')), 100);
echo "<br>";
echo "<br>";
echo "<br>";
echo htmlentities($stringHtml); //removes style and publishes html tags
echo ($stringHtml);
echo "<br>";
echo "<br>";
echo "<br>";
$concat1 = "Russ ";
$concat2 = "Wolf";
echo $concat1 .= $concat2;
echo "<br>";
echo "<br>";
echo "this is a \"lesson\" on escape commands.";
echo "<br>";
echo "<br>";
$product = 12345 * 67890;
echo $product;
echo "<br>";
echo substr($product, 3, 1);
echo "<br>";
echo substr($product, 3, 2);
echo "<br>";
echo "<br>";
echo "<br>";

echo "this is line " . __line__ . " of file " . __file__;
echo "<br>";
echo "this is line " . __line__ . " of file " . __file__;
echo "<br>";
echo "this is line " . __line__ . " of file " . __file__;
echo "<br>";
echo "this is line " . __line__ . " of file " . __file__;
echo "<br>";
echo "this is line " . __line__ . " of file " . __file__;
echo "<br>";
echo "this is line " . __line__ . " of file " . __file__;
echo "<br>";
echo "this is line " . __line__ . " of file " . __file__;
echo "<br>";
echo "this is line " . __line__ . " of file " . __file__;
echo "<br>";
echo "this is line " . __line__ . " of file " . __file__;


echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";









?>